### ISSUE TITLE
/Search-Engine-SmartSearch/search.php?key=: Fatal error: Uncaught Error: Call to a member function prepare() on null in \Search-Engine-SmartSearch\classes\SiteResultProvider.php:10 Stack trace: #0 \Search-Engine-SmartSearch\search.php(70): SiteResultProvider->getNumResult('') #1 {main} thrown in \Search-Engine-SmartSearch\classes\SiteResultProvider.php on line 10

### ISSUE THREAD

**Issue by dineshkummarc** [dineshkummarc/phpmySmartSearch#3]
/Search-Engine-SmartSearch/search.php?key=: Fatal error: Uncaught Error: Call to a member function prepare() on null in \Search-Engine-SmartSearch\classes\SiteResultProvider.php:10 Stack trace: #0 \Search-Engine-SmartSearch\search.php(70): SiteResultProvider->getNumResult('') #1 {main} thrown in \Search-Engine-SmartSearch\classes\SiteResultProvider.php on line 10

**Comment by dineshkummarc** [comment]
fixed
